In [37]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [38]:
df=pd.read_csv('auto-mpg.csv')

In [39]:
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object 
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car name      398 non-null    object 
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB


In [41]:
x=df.iloc[:,[2,4]]
y=df.iloc[:,5]

In [42]:
x.head()

displacement  weight
0         307.0    3504
1         350.0    3693
2         318.0    3436
3         304.0    3433
4         302.0    3449

In [43]:
y.head()

0    12.0
1    11.5
2    11.0
3    12.0
4    10.5
Name: acceleration, dtype: float64

In [44]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=40)

In [45]:
x_train.head()

displacement  weight
256         225.0    3430
295          98.0    1915
100         250.0    3021
253         200.0    3155
369         112.0    2395

In [46]:
scaler=StandardScaler().fit(x_train)

In [47]:
scaler

StandardScaler()

In [48]:
scaler.mean_

array([ 193.29362416, 2978.66107383])

In [49]:
scaled_value=scaler.transform(x_train)

In [50]:
scaled_value.mean(axis=0)

array([-9.53748639e-17, -2.14593444e-16])

In [51]:
x_test.head()

displacement  weight
142          79.0    1963
135         225.0    3613
77          121.0    2511
246          78.0    1985
118         116.0    2158

In [52]:
scaler=StandardScaler().fit(x_test)

In [53]:
scaler

StandardScaler()

In [54]:
scaled_yvalue=scaler.transform(x_test)

In [55]:
scaled_yvalue.mean(axis=0)

array([ 8.54871729e-17, -1.09912079e-16])